version: 2.1

executors:
  go-sdk:
    docker:
    - image: golang:alpine
      auth:
        username: $DOCKER_LOGIN
        password: $DOCKER_ACCESSTOKEN

jobs:
  build-app:
    executor: go-sdk
    steps:
      - checkout
      - run:
          name: Build
          command: go build

workflows:
  build-test-upload_image:
    jobs:
      - build-app:
          context: docker
          filters:
            tags:
              only: /.*/
